INSERT INTO activities (habit, description)
VALUES ('Sleep', 'Go to bed on time'),
       ('Sleep', 'Wake up on time'),
       ('Sleep', 'Turn off screens early'),
       ('Sleep', 'Read a bedtime story'),
       ('Sleep', 'Drink water before bed'),
       ('Sleep', 'Keep your room dark'),
       ('Sleep', 'Use a nightlight if needed'),
       ('Sleep', 'Take a warm bath'),
       ('Sleep', 'Avoid sweets before bedtime'),
       ('Sleep', 'Use a white noise machine'),
       ('Sleep', 'Skip sugary drinks evenings'),
       ('Sleep', 'Keep your room cool'),
       ('Sleep', 'Eat dinner early nightly'),
       ('Sleep', 'Practice deep breathing exercises'),
       ('Sleep', 'Write or draw at bedtime'),
       ('Sleep', 'Brush your teeth nightly'),
       ('Sleep', 'Stick to bedtime routine'),
       ('Sleep', 'Avoid late afternoon naps'),
       ('Sleep', 'Sleep 9 to 11 hours'),
       ('Sleep', 'Do light bedtime stretches'),
       ('Sleep', 'Spray calming lavender scent'),
       ('Sleep', 'Use your favorite blanket'),
       ('Sleep', 'Tidy up toys nightly'),
       ('Sleep', 'Use a soft alarm'),
       ('Sleep', 'Dim lights before bedtime'),
       ('Sleep', 'Play outside during daytime'),
       ('Sleep', 'Keep your bed for sleeping'),
       ('Sleep', 'Ask for a lullaby'),
       ('Sleep', 'Think happy thoughts nightly'),
       ('Sleep', 'Stay calm when waking up'),
       ('Sleep', 'Use a comfy pillow'),
       ('Sleep', 'Do quiet activities nightly'),
       ('Sleep', 'Count stars or sheep'),
       ('Sleep', 'Turn off noisy devices'),
       ('Sleep', 'Ask a parent to tuck in'),
       ('Sleep', 'Imagine fun dream scenes'),
       ('Sleep', 'Keep stuffed animals nearby'),
       ('Sleep', 'Skip scary bedtime stories'),
       ('Sleep', 'Use a small reading lamp'),
       ('Sleep', 'Do calming breathing games'),
       ('Sleep', 'Say goodnight to family'),
       ('Sleep', 'Wear comfy soft pajamas'),
       ('Sleep', 'Recall a happy memory'),
       ('Sleep', 'Avoid wild play before bed'),
       ('Sleep', 'Plan tomorrow before bed'),
       ('Sleep', 'Keep a bedtime book ready'),
       ('Sleep', 'Set bed with fresh sheets'),
       ('Sleep', 'Hum or sing to relax'),
       ('Sleep', 'Imagine peaceful scenes nightly'),
       ('Sleep', 'Draw or think of animals');