INSERT INTO activities (habit, description)
VALUES ('Sleep', 'Go to bed at the same time every night to feel rested'),
       ('Sleep', 'Wake up at the same time every morning for energy'),
       ('Sleep', 'Turn off all screens 1 hour before bedtime'),
       ('Sleep', 'Read your favorite bedtime story to relax'),
       ('Sleep', 'Drink a small glass of water before going to bed'),
       ('Sleep', 'Keep your room dark with curtains or blinds'),
       ('Sleep', 'Use a nightlight if you feel safer with it on'),
       ('Sleep', 'Take a warm bath or shower before bed to unwind'),
       ('Sleep', 'Avoid eating candy or sweets right before bedtime'),
       ('Sleep', 'Use a white noise machine to help you fall asleep'),
       ('Sleep', 'Do not drink soda or sugary drinks in the evening'),
       ('Sleep', 'Keep your room cool and cozy for a better sleep'),
       ('Sleep', 'Eat dinner early to give your tummy time to rest'),
       ('Sleep', 'Practice breathing deeply to calm down at night'),
       ('Sleep', 'Write or draw about your day in a bedtime journal'),
       ('Sleep', 'Brush your teeth every night before bed'),
       ('Sleep', 'Make a fun bedtime routine and stick to it'),
       ('Sleep', 'Avoid naps too close to bedtime'),
       ('Sleep', 'Sleep at least 9 to 11 hours each night to grow strong'),
       ('Sleep', 'Do light stretches before bedtime to relax your body'),
       ('Sleep', 'Spray a calming lavender scent in your room'),
       ('Sleep', 'Use your favorite blanket or stuffed animal to feel cozy'),
       ('Sleep', 'Keep your toys cleaned up to create a restful room'),
       ('Sleep', 'Use an alarm clock with soft sounds to wake up'),
       ('Sleep', 'Dim the lights in your room an hour before bedtime'),
       ('Sleep', 'Play outside during the day to feel sleepy at night'),
       ('Sleep', 'Keep your bed just for sleeping and relaxing'),
       ('Sleep', 'Ask a parent to sing or hum a lullaby to you'),
       ('Sleep', 'Practice smiling before bed to think happy thoughts'),
       ('Sleep', 'Stay calm if you wake up at night, and try relaxing'),
       ('Sleep', 'Go to bed with a clean and comfy pillow'),
       ('Sleep', 'Choose quiet activities like coloring before bed'),
       ('Sleep', 'Count stars, sheep, or your favorite animals to relax'),
       ('Sleep', 'Turn off loud or noisy devices before bedtime'),
       ('Sleep', 'Ask a parent to tuck you in snugly each night'),
       ('Sleep', 'Imagine fun dreams about your favorite place'),
       ('Sleep', 'Keep stuffed animals in a cozy spot near your bed'),
       ('Sleep', 'Avoid scary stories or movies before bed'),
       ('Sleep', 'Turn off big lights and use a small reading lamp'),
       ('Sleep', 'Do a fun breathing game to settle down at night'),
       ('Sleep', 'Say goodnight to family members before bed'),
       ('Sleep', 'Pick pajamas that are soft and comfy'),
       ('Sleep', 'Ask a parent to talk about a happy memory'),
       ('Sleep', 'Avoid jumping or playing too wildly before bedtime'),
       ('Sleep', 'Plan what you’ll do tomorrow before going to sleep'),
       ('Sleep', 'Keep a favorite bedtime book ready to read'),
       ('Sleep', 'Help set up your bed with fresh blankets or sheets'),
       ('Sleep', 'Sing or hum a calming tune to yourself in bed'),
       ('Sleep', 'Visualize calm and peaceful scenes before bed'),
       ('Sleep', 'Draw or think about your favorite animal as you relax');