INSERT INTO activities (habit, description)
VALUES ('Sleep', 'Go to bed at the same time daily'),
       ('Sleep', 'Wake up at the same time daily'),
       ('Sleep', 'Turn off screens 1 hour before bed'),
       ('Sleep', 'Read a bedtime story to relax'),
       ('Sleep', 'Drink water before going to bed'),
       ('Sleep', 'Keep your room dark with curtains'),
       ('Sleep', 'Use a nightlight if it feels safer'),
       ('Sleep', 'Take a warm bath or shower before bed'),
       ('Sleep', 'Avoid candy or sweets before bedtime'),
       ('Sleep', 'Use a white noise machine for better sleep'),
       ('Sleep', 'Skip soda or sugary drinks in the evening'),
       ('Sleep', 'Keep your room cool for better sleep'),
       ('Sleep', 'Eat dinner early to rest your tummy'),
       ('Sleep', 'Practice deep breathing to relax'),
       ('Sleep', 'Write or draw in a bedtime journal'),
       ('Sleep', 'Brush your teeth every night before bed'),
       ('Sleep', 'Stick to a fun bedtime routine'),
       ('Sleep', 'Avoid naps too close to bedtime'),
       ('Sleep', 'Sleep 9 to 11 hours every night'),
       ('Sleep', 'Do light stretches to relax before bed'),
       ('Sleep', 'Spray calming lavender in your room'),
       ('Sleep', 'Use your favorite blanket for comfort'),
       ('Sleep', 'Tidy up toys for a restful room'),
       ('Sleep', 'Use an alarm with soft sounds'),
       ('Sleep', 'Dim the lights an hour before bed'),
       ('Sleep', 'Play outside to feel sleepy at night'),
       ('Sleep', 'Keep your bed just for sleeping'),
       ('Sleep', 'Ask for a lullaby before sleeping'),
       ('Sleep', 'Think happy thoughts before bed'),
       ('Sleep', 'Stay calm if you wake up at night'),
       ('Sleep', 'Use a clean and comfy pillow'),
       ('Sleep', 'Do quiet activities before bed'),
       ('Sleep', 'Count stars or sheep to relax'),
       ('Sleep', 'Turn off noisy devices before bed'),
       ('Sleep', 'Ask a parent to tuck you in snugly'),
       ('Sleep', 'Imagine fun dreams before sleeping'),
       ('Sleep', 'Keep stuffed animals near your bed'),
       ('Sleep', 'Skip scary stories before bed'),
       ('Sleep', 'Use a small reading lamp at night'),
       ('Sleep', 'Do a breathing game to settle down'),
       ('Sleep', 'Say goodnight to family members'),
       ('Sleep', 'Pick soft and comfy pajamas'),
       ('Sleep', 'Think about a happy memory'),
       ('Sleep', 'Avoid jumping or playing wildly before bed'),
       ('Sleep', 'Plan tomorrow’s activities before bed'),
       ('Sleep', 'Keep a favorite bedtime book ready'),
       ('Sleep', 'Set your bed with fresh blankets'),
       ('Sleep', 'Hum or sing a calming tune to yourself'),
       ('Sleep', 'Think of peaceful scenes to relax'),
       ('Sleep', 'Draw or think about a favorite animal');