INSERT INTO activities (habit, description)
VALUES ('Exercise', 'Do 10 jumping jacks'),
       ('Exercise', 'Run in place for 1 minute'),
       ('Exercise', 'Play tag with friends or family'),
       ('Exercise', 'Go for a walk nearby'),
       ('Exercise', 'Dance to a song for 5 minutes'),
       ('Exercise', 'Hop on one foot 10 times'),
       ('Exercise', 'Stretch your arms and legs'),
       ('Exercise', 'Walk like a crab or bear'),
       ('Exercise', 'Try a new sport or activity'),
       ('Exercise', 'Kick a ball with a friend'),
       ('Exercise', 'Ride your bike or scooter'),
       ('Exercise', 'Jump rope for 5 minutes'),
       ('Exercise', 'Balance on one foot for 10 seconds'),
       ('Exercise', 'Throw and catch a ball'),
       ('Exercise', 'Play on the playground'),
       ('Exercise', 'Climb or swing on monkey bars'),
       ('Exercise', 'Do a somersault or cartwheel'),
       ('Exercise', 'Play hide-and-seek outside'),
       ('Exercise', 'Jump as high as you can 10 times'),
       ('Exercise', 'Do an obstacle course'),
       ('Exercise', 'Move like your favorite animal'),
       ('Exercise', 'Try to do 5 push-ups'),
       ('Exercise', 'Do 10 sit-ups'),
       ('Exercise', 'Spin in circles for 30 seconds'),
       ('Exercise', 'Do a scavenger hunt'),
       ('Exercise', 'Race a friend outside'),
       ('Exercise', 'Pretend to be a frog and hop'),
       ('Exercise', 'Skip across the yard or driveway'),
       ('Exercise', 'Do 10 lunges'),
       ('Exercise', 'Play hopscotch or jump rope'),
       ('Exercise', 'Hold a plank as long as you can'),
       ('Exercise', 'Learn a new dance routine'),
       ('Exercise', 'Throw a frisbee with a friend'),
       ('Exercise', 'Jump up and touch something high'),
       ('Exercise', 'Balance a toy on your head'),
       ('Exercise', 'Pretend to swim on the floor'),
       ('Exercise', 'Walk a dog or pretend to walk one'),
       ('Exercise', 'Play freeze dance'),
       ('Exercise', 'Do a family relay race'),
       ('Exercise', 'Try a yoga pose'),
       ('Exercise', 'Do 5 squats'),
       ('Exercise', 'Clap while jumping'),
       ('Exercise', 'Shuffle side-to-side for 1 minute'),
       ('Exercise', 'Pretend to climb a mountain'),
       ('Exercise', 'Do a star jump'),
       ('Exercise', 'Run back and forth 5 times'),
       ('Exercise', 'Pretend to hula hoop'),
       ('Exercise', 'Make up a running game'),
       ('Exercise', 'March in place with high knees'),
       ('Exercise', 'Do a wall sit for 20 seconds');