INSERT INTO activities (habit, description)
VALUES ('Exercise', 'Do 10 jumping jacks'),
       ('Exercise', 'Run in place'),
       ('Exercise', 'Play tag with friends'),
       ('Exercise', 'Go for a walk'),
       ('Exercise', 'Dance for 5 minutes'),
       ('Exercise', 'Hop on one foot'),
       ('Exercise', 'Stretch arms and legs'),
       ('Exercise', 'Walk like a crab'),
       ('Exercise', 'Try a new sport'),
       ('Exercise', 'Kick a ball'),
       ('Exercise', 'Ride your bike'),
       ('Exercise', 'Jump rope 5 minutes'),
       ('Exercise', 'Balance on one foot'),
       ('Exercise', 'Throw and catch'),
       ('Exercise', 'Play on playground'),
       ('Exercise', 'Climb monkey bars'),
       ('Exercise', 'Do a somersault'),
       ('Exercise', 'Play hide-and-seek'),
       ('Exercise', 'Jump as high as possible'),
       ('Exercise', 'Do an obstacle course'),
       ('Exercise', 'Move like an animal'),
       ('Exercise', 'Do 5 push-ups'),
       ('Exercise', 'Do 10 sit-ups'),
       ('Exercise', 'Spin in circles'),
       ('Exercise', 'Do a scavenger hunt'),
       ('Exercise', 'Race a friend'),
       ('Exercise', 'Pretend to be a frog'),
       ('Exercise', 'Skip across yard'),
       ('Exercise', 'Do 10 lunges'),
       ('Exercise', 'Play hopscotch'),
       ('Exercise', 'Hold a plank'),
       ('Exercise', 'Learn a dance routine'),
       ('Exercise', 'Throw a frisbee'),
       ('Exercise', 'Jump and touch something'),
       ('Exercise', 'Balance a toy'),
       ('Exercise', 'Pretend to swim'),
       ('Exercise', 'Walk a dog'),
       ('Exercise', 'Play freeze dance'),
       ('Exercise', 'Do a relay race'),
       ('Exercise', 'Try a yoga pose'),
       ('Exercise', 'Do 5 squats'),
       ('Exercise', 'Clap and jump'),
       ('Exercise', 'Shuffle side-to-side'),
       ('Exercise', 'Climb a pretend mountain'),
       ('Exercise', 'Do a star jump'),
       ('Exercise', 'Run back and forth'),
       ('Exercise', 'Pretend to hula hoop'),
       ('Exercise', 'Make a running game'),
       ('Exercise', 'March with high knees'),
       ('Exercise', 'Do a wall sit');