INSERT INTO activities (habit, description)
VALUES ('Exercise', 'Do 10 jumping jacks with high jumps'),
       ('Exercise', 'Run in place for 1 minute fast'),
       ('Exercise', 'Play tag with friends outside'),
       ('Exercise', 'Go for a 10-minute walk'),
       ('Exercise', 'Dance to your favorite song'),
       ('Exercise', 'Hop on one foot 10 times each'),
       ('Exercise', 'Do morning stretches for 2 minutes'),
       ('Exercise', 'Walk like a crab across the room'),
       ('Exercise', 'Try a new sport with friends'),
       ('Exercise', 'Kick a ball 20 times straight'),
       ('Exercise', 'Ride your bike for 10 minutes'),
       ('Exercise', 'Jump rope to a fun song'),
       ('Exercise', 'Balance on each foot for 30 seconds'),
       ('Exercise', 'Play catch with 10 good throws'),
       ('Exercise', 'Play on playground for 15 minutes'),
       ('Exercise', 'Do 3 monkey bar moves'),
       ('Exercise', 'Do a safe forward roll'),
       ('Exercise', 'Play hide-and-seek for 10 minutes'),
       ('Exercise', 'Jump and touch something high up'),
       ('Exercise', 'Create a fun obstacle course'),
       ('Exercise', 'Move like your favorite animal'),
       ('Exercise', 'Do 5 perfect push-ups'),
       ('Exercise', 'Do 10 careful sit-ups'),
       ('Exercise', 'Spin and dance for 1 minute'),
       ('Exercise', 'Find 5 things in scavenger hunt'),
       ('Exercise', 'Race a friend to a target'),
       ('Exercise', 'Hop like a frog 10 times'),
       ('Exercise', 'Skip across the yard twice'),
       ('Exercise', 'Do 10 big walking lunges'),
       ('Exercise', 'Draw and play hopscotch'),
       ('Exercise', 'Hold plank pose for 20 seconds'),
       ('Exercise', 'Learn 3 new dance moves'),
       ('Exercise', 'Play frisbee for 10 minutes'),
       ('Exercise', 'Touch 5 different heights'),
       ('Exercise', 'Balance a book while walking'),
       ('Exercise', 'Do swimming movements for 1 minute'),
       ('Exercise', 'Walk the dog around block'),
       ('Exercise', 'Dance-freeze to 2 songs'),
       ('Exercise', 'Make and run a fun relay'),
       ('Exercise', 'Try tree pose for 30 seconds'),
       ('Exercise', 'Do 5 strong squats'),
       ('Exercise', 'Jump and clap 15 times'),
       ('Exercise', 'Shuffle sideways 20 steps each way'),
       ('Exercise', 'Pretend climb a tall mountain'),
       ('Exercise', 'Do 5 super star jumps'),
       ('Exercise', 'Run zigzag in the yard'),
       ('Exercise', 'Hula hoop with arm circles'),
       ('Exercise', 'Invent a new running game'),
       ('Exercise', 'March with knees high 30 steps'),
       ('Exercise', 'Hold wall sit for 20 seconds');