INSERT INTO activities (habit, description)
VALUES
    ('Diet', 'Eat fruit at breakfast'),
    ('Diet', 'Try a new vegetable'),
    ('Diet', 'Drink water not soda'),
    ('Diet', 'Pack a healthy lunch'),
    ('Diet', 'Eat a colorful plate'),
    ('Diet', 'Choose whole grain bread'),
    ('Diet', 'Snack on fruit'),
    ('Diet', 'Eat eggs or nuts'),
    ('Diet', 'Try a veggie smoothie'),
    ('Diet', 'Eat slowly and chew'),
    ('Diet', 'Avoid eating while watching'),
    ('Diet', 'Use hummus as dip'),
    ('Diet', 'Drink water before meals'),
    ('Diet', 'Make a snack with family'),
    ('Diet', 'Eat yogurt or cheese'),
    ('Diet', 'Pick healthy groceries'),
    ('Diet', 'Avoid eating too many sweets'),
    ('Diet', 'Eat green veggies'),
    ('Diet', 'Make a veggie sandwich'),
    ('Diet', 'Try a new fruit'),
    ('Diet', 'Eat breakfast every day'),
    ('Diet', 'Snack on nuts'),
    ('Diet', 'Choose fish over fried'),
    ('Diet', 'Help cook healthy dinner'),
    ('Diet', 'Add veggies to pizza'),
    ('Diet', 'Eat a salad'),
    ('Diet', 'Drink plain water'),
    ('Diet', 'Make a fruit salad'),
    ('Diet', 'Eat oats or grains'),
    ('Diet', 'Choose baked not fried'),
    ('Diet', 'Add spinach to smoothie'),
    ('Diet', 'Make a veggie wrap'),
    ('Diet', 'Replace dessert with fruit'),
    ('Diet', 'Snack on dried fruit'),
    ('Diet', 'Try peanut butter toast'),
    ('Diet', 'Eat a boiled egg'),
    ('Diet', 'Dip apples in peanut butter'),
    ('Diet', 'Eat dark chocolate'),
    ('Diet', 'Eat oatmeal with fruit'),
    ('Diet', 'Wash fruits and veggies'),
    ('Diet', 'Add berries to cereal'),
    ('Diet', 'Eat an orange'),
    ('Diet', 'Skip sugary drinks'),
    ('Diet', 'Learn portion sizes'),
    ('Diet', 'Snack on carrots'),
    ('Diet', 'Drink milk with meals'),
    ('Diet', 'Make trail mix'),
    ('Diet', 'Peel fruits for dinner'),
    ('Diet', 'Eat frozen bananas'),
    ('Diet', 'Eat veggie soup');