INSERT INTO activities (habit, description)
VALUES ('Diet', 'Eat a fruit with your breakfast'),
       ('Diet', 'Try a new vegetable today'),
       ('Diet', 'Drink water instead of soda or juice'),
       ('Diet', 'Help pack a healthy lunch for school'),
       ('Diet', 'Eat a colorful plate with at least 3 colors'),
       ('Diet', 'Choose whole grain bread instead of white'),
       ('Diet', 'Have a snack of fresh fruit or vegetables'),
       ('Diet', 'Eat a protein-rich food like eggs or nuts'),
       ('Diet', 'Try a smoothie with fruits and veggies'),
       ('Diet', 'Eat slowly and chew your food well'),
       ('Diet', 'Avoid eating while watching TV or playing games'),
       ('Diet', 'Choose a healthy dip like hummus with veggies'),
       ('Diet', 'Drink a glass of water before each meal'),
       ('Diet', 'Make a healthy snack with your family'),
       ('Diet', 'Try a dairy product like yogurt or cheese'),
       ('Diet', 'Help pick out healthy groceries at the store'),
       ('Diet', 'Avoid eating too many sweets or candy'),
       ('Diet', 'Eat a serving of green vegetables at dinner'),
       ('Diet', 'Make your own healthy sandwich with veggies'),
       ('Diet', 'Try a new fruit you’ve never tasted before'),
       ('Diet', 'Eat breakfast every day to start your morning right'),
       ('Diet', 'Snack on a handful of nuts or seeds'),
       ('Diet', 'Have fish or chicken instead of fried food'),
       ('Diet', 'Help prepare a healthy dinner with your family'),
       ('Diet', 'Add a new veggie topping to your pizza'),
       ('Diet', 'Try a salad with your favorite dressing'),
       ('Diet', 'Choose plain water over flavored drinks'),
       ('Diet', 'Make a fruit salad with at least 3 fruits'),
       ('Diet', 'Eat something with fiber, like oats or whole grains'),
       ('Diet', 'Choose a baked snack instead of fried'),
       ('Diet', 'Add spinach or kale to your smoothie'),
       ('Diet', 'Make a veggie wrap for lunch'),
       ('Diet', 'Replace a sugary dessert with fresh fruit'),
       ('Diet', 'Have a small handful of raisins or dried fruit'),
       ('Diet', 'Try a nut butter like almond or peanut on toast'),
       ('Diet', 'Have a boiled egg as part of your breakfast'),
       ('Diet', 'Dip apple slices in peanut butter for a snack'),
       ('Diet', 'Choose a small piece of dark chocolate instead of candy'),
       ('Diet', 'Eat oatmeal with fruit for a healthy breakfast'),
       ('Diet', 'Help wash fruits and veggies for the family'),
       ('Diet', 'Add berries to your cereal or yogurt'),
       ('Diet', 'Eat an orange or tangerine for vitamin C'),
       ('Diet', 'Avoid sugary drinks like soda for the whole day'),
       ('Diet', 'Learn how to measure a portion size with your hands'),
       ('Diet', 'Snack on crunchy carrot or celery sticks'),
       ('Diet', 'Drink milk or a dairy alternative with your meal'),
       ('Diet', 'Make a trail mix with nuts and dried fruit'),
       ('Diet', 'Help peel fruits or vegetables for dinner'),
       ('Diet', 'Eat a healthy dessert, like frozen banana slices'),
       ('Diet', 'Have soup with vegetables for lunch or dinner');