INSERT INTO activities (habit, description)
VALUES ('Diet', 'Eat a fruit with breakfast'),
       ('Diet', 'Try a new vegetable'),
       ('Diet', 'Drink water instead of soda'),
       ('Diet', 'Pack a healthy lunch for school'),
       ('Diet', 'Eat a colorful plate with 3 colors'),
       ('Diet', 'Choose whole grain bread'),
       ('Diet', 'Snack on fruit or veggies'),
       ('Diet', 'Eat protein like eggs or nuts'),
       ('Diet', 'Try a fruit and veggie smoothie'),
       ('Diet', 'Eat slowly and chew well'),
       ('Diet', 'Avoid eating while watching TV'),
       ('Diet', 'Use hummus with veggies as a dip'),
       ('Diet', 'Drink water before meals'),
       ('Diet', 'Make a healthy snack with family'),
       ('Diet', 'Eat yogurt or cheese'),
       ('Diet', 'Help pick healthy groceries'),
       ('Diet', 'Avoid eating too many sweets'),
       ('Diet', 'Eat green veggies at dinner'),
       ('Diet', 'Make a veggie-filled sandwich'),
       ('Diet', 'Try a new fruit today'),
       ('Diet', 'Eat breakfast every day'),
       ('Diet', 'Snack on nuts or seeds'),
       ('Diet', 'Choose fish or chicken over fried food'),
       ('Diet', 'Help make a healthy dinner'),
       ('Diet', 'Add veggies to your pizza'),
       ('Diet', 'Eat a salad with dressing'),
       ('Diet', 'Drink plain water, not flavored drinks'),
       ('Diet', 'Make a fruit salad with 3 fruits'),
       ('Diet', 'Eat fiber like oats or grains'),
       ('Diet', 'Choose baked snacks, not fried'),
       ('Diet', 'Add spinach to your smoothie'),
       ('Diet', 'Make a veggie wrap for lunch'),
       ('Diet', 'Replace dessert with fresh fruit'),
       ('Diet', 'Snack on raisins or dried fruit'),
       ('Diet', 'Try almond or peanut butter on toast'),
       ('Diet', 'Eat a boiled egg for breakfast'),
       ('Diet', 'Dip apple slices in peanut butter'),
       ('Diet', 'Have dark chocolate instead of candy'),
       ('Diet', 'Eat oatmeal with fruit'),
       ('Diet', 'Wash fruits and veggies for family'),
       ('Diet', 'Add berries to cereal or yogurt'),
       ('Diet', 'Eat an orange for vitamin C'),
       ('Diet', 'Skip sugary drinks like soda'),
       ('Diet', 'Learn portion sizes using hands'),
       ('Diet', 'Snack on carrot or celery sticks'),
       ('Diet', 'Drink milk with your meal'),
       ('Diet', 'Make trail mix with nuts and fruit'),
       ('Diet', 'Peel fruits or veggies for dinner'),
       ('Diet', 'Eat frozen bananas as dessert'),
       ('Diet', 'Have veggie soup for lunch');