INSERT INTO activities (habit, description)
VALUES ('Kindness', 'Say “thank you”'),
       ('Kindness', 'Help a friend'),
       ('Kindness', 'Give a compliment'),
       ('Kindness', 'Draw a picture'),
       ('Kindness', 'Say something nice'),
       ('Kindness', 'Pick up litter'),
       ('Kindness', 'Share your toys'),
       ('Kindness', 'Write a thank-you note'),
       ('Kindness', 'Hold the door open'),
       ('Kindness', 'Let someone go ahead'),
       ('Kindness', 'Smile at people'),
       ('Kindness', 'Ask about someone’s day'),
       ('Kindness', 'Help with chores'),
       ('Kindness', 'Give a family hug'),
       ('Kindness', 'Tell a friend you care'),
       ('Kindness', 'Help a younger child'),
       ('Kindness', 'Say “please” politely'),
       ('Kindness', 'Make a card'),
       ('Kindness', 'Tell a teacher they’re great'),
       ('Kindness', 'Share snacks at lunch'),
       ('Kindness', 'Help set the table'),
       ('Kindness', 'Give a high-five'),
       ('Kindness', 'Say something nice to siblings'),
       ('Kindness', 'Water plants or pets'),
       ('Kindness', 'Say “sorry” if needed'),
       ('Kindness', 'Ask if someone needs help'),
       ('Kindness', 'Make a thoughtful gift'),
       ('Kindness', 'Carry groceries inside'),
       ('Kindness', 'Tell a funny joke'),
       ('Kindness', 'Clean a mess'),
       ('Kindness', 'Share your seat'),
       ('Kindness', 'Write a kind note'),
       ('Kindness', 'Say “good job”'),
       ('Kindness', 'Help with homework'),
       ('Kindness', 'Say “excuse me” politely'),
       ('Kindness', 'Clean your room'),
       ('Kindness', 'Wave and say “hi”'),
       ('Kindness', 'Play with someone lonely'),
       ('Kindness', 'Help clean sibling’s toys'),
       ('Kindness', 'Tell grandparents you love them'),
       ('Kindness', 'Share art supplies'),
       ('Kindness', 'Make a small donation'),
       ('Kindness', 'Draw and share happiness'),
       ('Kindness', 'Help carry something'),
       ('Kindness', 'Cheer for a friend'),
       ('Kindness', 'Pick flowers for someone'),
       ('Kindness', 'Help tie shoes'),
       ('Kindness', 'Say “you’re awesome”'),
       ('Kindness', 'Write a nice note');