INSERT INTO activities (habit, description)
VALUES ('Kindness', 'Say "thank you" to 3 people today'),
       ('Kindness', 'Help a friend with a task'),
       ('Kindness', 'Give someone a specific compliment'),
       ('Kindness', 'Draw a picture for someone special'),
       ('Kindness', 'Tell someone why they matter'),
       ('Kindness', 'Pick up 5 pieces of litter safely'),
       ('Kindness', 'Share your favorite toy today'),
       ('Kindness', 'Write a thank-you note to helper'),
       ('Kindness', 'Hold the door for 2 people'),
       ('Kindness', 'Let someone go first in line'),
       ('Kindness', 'Share 5 smiles with others'),
       ('Kindness', 'Ask how someones day was'),
       ('Kindness', 'Help with 2 family chores'),
       ('Kindness', 'Give a big family group hug'),
       ('Kindness', 'Tell a friend why theyre special'),
       ('Kindness', 'Help teach something you know'),
       ('Kindness', 'Use "please" 5 times today'),
       ('Kindness', 'Make a card to brighten day'),
       ('Kindness', 'Thank teacher for helping you'),
       ('Kindness', 'Share a healthy snack with friend'),
       ('Kindness', 'Set the table without being asked'),
       ('Kindness', 'Give 3 happy high-fives'),
       ('Kindness', 'Say what you love about sibling'),
       ('Kindness', 'Care for a plant or pet today'),
       ('Kindness', 'Say sorry and really mean it'),
       ('Kindness', 'Offer help before being asked'),
       ('Kindness', 'Make a handmade gift for someone'),
       ('Kindness', 'Help carry in family groceries'),
       ('Kindness', 'Share a joke to make someone laugh'),
       ('Kindness', 'Clean up without being told'),
       ('Kindness', 'Offer your seat to someone'),
       ('Kindness', 'Leave a happy surprise note'),
       ('Kindness', 'Celebrate someones success'),
       ('Kindness', 'Help friend learn something new'),
       ('Kindness', 'Use good manners all morning'),
       ('Kindness', 'Clean room as a surprise'),
       ('Kindness', 'Greet 5 people with a smile'),
       ('Kindness', 'Include someone in your game'),
       ('Kindness', 'Help sibling with their task'),
       ('Kindness', 'Call grandparents to say hi'),
       ('Kindness', 'Share art supplies with others'),
       ('Kindness', 'Give away toy to someone in need'),
       ('Kindness', 'Make happiness cards for others'),
       ('Kindness', 'Help someone carry something'),
       ('Kindness', 'Be someones biggest fan today'),
       ('Kindness', 'Give flowers you picked safely'),
       ('Kindness', 'Help younger kid tie shoes'),
       ('Kindness', 'Write 3 kind notes for others'),
       ('Kindness', 'Make someone feel welcome');