INSERT INTO activities (habit, description)
VALUES ('Kindness', 'Say “thank you” to someone'),
       ('Kindness', 'Help a friend or sibling'),
       ('Kindness', 'Give a compliment to someone'),
       ('Kindness', 'Draw a picture for family'),
       ('Kindness', 'Say something nice to a teacher'),
       ('Kindness', 'Pick up litter and trash'),
       ('Kindness', 'Share your toys with someone'),
       ('Kindness', 'Write a thank-you note'),
       ('Kindness', 'Hold the door open'),
       ('Kindness', 'Let someone go ahead in line'),
       ('Kindness', 'Smile at people you meet'),
       ('Kindness', 'Ask someone how their day is'),
       ('Kindness', 'Help with chores at home'),
       ('Kindness', 'Give a hug to family'),
       ('Kindness', 'Tell a friend you like them'),
       ('Kindness', 'Help a younger child'),
       ('Kindness', 'Say “please” when asking'),
       ('Kindness', 'Make a card for someone sad'),
       ('Kindness', 'Tell your teacher they’re great'),
       ('Kindness', 'Share snacks at lunch'),
       ('Kindness', 'Help set the dinner table'),
       ('Kindness', 'Give a high-five to someone'),
       ('Kindness', 'Tell your sibling something nice'),
       ('Kindness', 'Help water plants or pets'),
       ('Kindness', 'Say “sorry” if you hurt someone'),
       ('Kindness', 'Ask if someone needs help'),
       ('Kindness', 'Make a gift for someone'),
       ('Kindness', 'Carry groceries into the house'),
       ('Kindness', 'Tell someone a funny joke'),
       ('Kindness', 'Clean up a mess you didn’t make'),
       ('Kindness', 'Share your seat with someone'),
       ('Kindness', 'Write a kind sticky note'),
       ('Kindness', 'Say “good job” to someone'),
       ('Kindness', 'Help a friend with homework'),
       ('Kindness', 'Say “excuse me” if you bump someone'),
       ('Kindness', 'Clean your room without asking'),
       ('Kindness', 'Wave and say “hi” to neighbors'),
       ('Kindness', 'Play with someone who is lonely'),
       ('Kindness', 'Help a sibling clean their toys'),
       ('Kindness', 'Tell grandparents you love them'),
       ('Kindness', 'Share art supplies with a friend'),
       ('Kindness', 'Make a donation or small gift'),
       ('Kindness', 'Draw and give a happy picture'),
       ('Kindness', 'Help carry something heavy'),
       ('Kindness', 'Cheer for a friend at a game'),
       ('Kindness', 'Pick flowers and give them to someone'),
       ('Kindness', 'Help tie someone’s shoes'),
       ('Kindness', 'Say “you’re awesome” to someone'),
       ('Kindness', 'Write a nice note for your parents');