INSERT INTO activities (habit, description)
VALUES ('Organization', 'Make your bed extra neat'),
       ('Organization', 'Sort toys into colored bins'),
       ('Organization', 'Put clean clothes in drawers'),
       ('Organization', 'Help fold 5 pieces of laundry'),
       ('Organization', 'Line up school supplies neatly'),
       ('Organization', 'Clean art space for 5 minutes'),
       ('Organization', 'Arrange books by size or color'),
       ('Organization', 'Put all shoes in their spot'),
       ('Organization', 'Set table with all items'),
       ('Organization', 'Fill one trash bag today'),
       ('Organization', 'Create labels for toy bins'),
       ('Organization', 'Clean desk with wet wipe'),
       ('Organization', 'Put jackets on hooks nicely'),
       ('Organization', 'File papers in folders'),
       ('Organization', 'Help load dishwasher safely'),
       ('Organization', 'Sort art supplies by type'),
       ('Organization', 'Pack backpack for tomorrow'),
       ('Organization', 'Help vacuum one room'),
       ('Organization', 'Match 5 pairs of socks'),
       ('Organization', 'Line up stuffed animals'),
       ('Organization', 'Pick up 10 things in room'),
       ('Organization', 'Make desk neat and tidy'),
       ('Organization', 'Sort groceries by type'),
       ('Organization', 'Make sock pairs drawer'),
       ('Organization', 'Clear dishes after meal'),
       ('Organization', 'Use trash can properly'),
       ('Organization', 'Help organize toy chest'),
       ('Organization', 'Give plants fresh water'),
       ('Organization', 'Stack games on shelf neatly'),
       ('Organization', 'Wipe table after eating'),
       ('Organization', 'Park bike in right spot'),
       ('Organization', 'Clean out car cup holders'),
       ('Organization', 'Write todays to-do list'),
       ('Organization', 'Make toy display pretty'),
       ('Organization', 'Dust three surfaces well'),
       ('Organization', 'Use hamper for all clothes'),
       ('Organization', 'Sort items for recycling'),
       ('Organization', 'Sweep front step clean'),
       ('Organization', 'Organize bathroom items'),
       ('Organization', 'Stack games by size'),
       ('Organization', 'Clean one window safely'),
       ('Organization', 'Line up shoes by pairs'),
       ('Organization', 'Put food in containers'),
       ('Organization', 'Sort books by topic'),
       ('Organization', 'Clean pet area nicely'),
       ('Organization', 'Make toy bins organized'),
       ('Organization', 'Sort papers into piles'),
       ('Organization', 'Put water bottle in spot'),
       ('Organization', 'Choose clothes for tomorrow'),
       ('Organization', 'Make play area tidy');