INSERT INTO activities (habit, description)
VALUES
    ('Organization', 'Make your bed every morning'),
    ('Organization', 'Put toys back in their place'),
    ('Organization', 'Sort clothes into clean and dirty'),
    ('Organization', 'Fold laundry with parents'),
    ('Organization', 'Organize school supplies in your bag'),
    ('Organization', 'Clean up your craft area'),
    ('Organization', 'Stack books neatly on shelves'),
    ('Organization', 'Put shoes in their spot'),
    ('Organization', 'Set the table for meals'),
    ('Organization', 'Pick up trash in your room'),
    ('Organization', 'Sort toys into bins or boxes'),
    ('Organization', 'Wipe down your desk or table'),
    ('Organization', 'Hang up your jacket or coat'),
    ('Organization', 'Put homework in your folder'),
    ('Organization', 'Load or unload the dishwasher'),
    ('Organization', 'Organize crayons or markers by color'),
    ('Organization', 'Pack your lunchbox neatly'),
    ('Organization', 'Sweep or vacuum a small area'),
    ('Organization', 'Sort clothes into drawers by type'),
    ('Organization', 'Put stuffed animals in one spot'),
    ('Organization', 'Tidy the living room before bed'),
    ('Organization', 'Clear and organize your desk'),
    ('Organization', 'Put away groceries in the right spots'),
    ('Organization', 'Match socks while folding laundry'),
    ('Organization', 'Put dishes in the sink after eating'),
    ('Organization', 'Throw away papers or scraps'),
    ('Organization', 'Help clean up your sibling’s toys'),
    ('Organization', 'Water houseplants and tidy up'),
    ('Organization', 'Stack puzzles or games neatly'),
    ('Organization', 'Wipe crumbs off the table'),
    ('Organization', 'Put your bike in its spot'),
    ('Organization', 'Pick up trash from the car'),
    ('Organization', 'Make a checklist for your day'),
    ('Organization', 'Organize toys in a display'),
    ('Organization', 'Dust furniture in the living room'),
    ('Organization', 'Place dirty clothes in the hamper'),
    ('Organization', 'Sort and recycle paper or cans'),
    ('Organization', 'Sweep leaves or dirt off the porch'),
    ('Organization', 'Tidy your bathroom counter'),
    ('Organization', 'Put away games after playing'),
    ('Organization', 'Help wash windows with a parent'),
    ('Organization', 'Straighten shoes in the entryway'),
    ('Organization', 'Put away leftover food'),
    ('Organization', 'Organize the family’s bookshelf'),
    ('Organization', 'Clean your pet’s space'),
    ('Organization', 'Write labels for toy bins'),
    ('Organization', 'Sort mail or papers with a parent'),
    ('Organization', 'Keep your water bottle in its spot'),
    ('Organization', 'Plan and set out tomorrow’s outfit'),
    ('Organization', 'Clean your play area or backyard');