INSERT INTO activities (habit, description)
VALUES ('Organization', 'Make your bed'),
       ('Organization', 'Put toys in place'),
       ('Organization', 'Sort clean and dirty clothes'),
       ('Organization', 'Fold laundry with parents'),
       ('Organization', 'Organize school supplies'),
       ('Organization', 'Clean your craft area'),
       ('Organization', 'Stack books neatly'),
       ('Organization', 'Put shoes in spot'),
       ('Organization', 'Set the table'),
       ('Organization', 'Pick up room trash'),
       ('Organization', 'Sort toys into bins'),
       ('Organization', 'Wipe desk or table'),
       ('Organization', 'Hang up your jacket'),
       ('Organization', 'Put homework in folder'),
       ('Organization', 'Load the dishwasher'),
       ('Organization', 'Organize crayons by color'),
       ('Organization', 'Pack your lunchbox'),
       ('Organization', 'Sweep or vacuum floor'),
       ('Organization', 'Sort clothes into drawers'),
       ('Organization', 'Put stuffed animals together'),
       ('Organization', 'Tidy living room'),
       ('Organization', 'Clear and organize desk'),
       ('Organization', 'Put away groceries'),
       ('Organization', 'Match socks while folding'),
       ('Organization', 'Put dishes in sink'),
       ('Organization', 'Throw away scraps'),
       ('Organization', 'Clean sibling’s toys'),
       ('Organization', 'Water and tidy plants'),
       ('Organization', 'Stack puzzles neatly'),
       ('Organization', 'Wipe crumbs off table'),
       ('Organization', 'Put bike in spot'),
       ('Organization', 'Pick trash from car'),
       ('Organization', 'Make a daily checklist'),
       ('Organization', 'Organize toys for display'),
       ('Organization', 'Dust living room furniture'),
       ('Organization', 'Put clothes in hamper'),
       ('Organization', 'Sort and recycle items'),
       ('Organization', 'Sweep leaves from porch'),
       ('Organization', 'Tidy bathroom counter'),
       ('Organization', 'Put away games'),
       ('Organization', 'Wash windows with parent'),
       ('Organization', 'Straighten entryway shoes'),
       ('Organization', 'Put away leftover food'),
       ('Organization', 'Organize family bookshelf'),
       ('Organization', 'Clean pet’s space'),
       ('Organization', 'Label toy bins'),
       ('Organization', 'Sort papers with parent'),
       ('Organization', 'Place water bottle'),
       ('Organization', 'Plan tomorrow’s outfit'),
       ('Organization', 'Clean play area');